services:
  mysql:
    image: mysql:8.0   # MySQL version 8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword      # Root password for MySQL
      MYSQL_DATABASE: mydatabase             # Database name to initialize
      MYSQL_USER: user                      # Custom user
      MYSQL_PASSWORD: password              # Password for custom user
    volumes:
      - ./mysql_data:/var/lib/mysql          # Persist database data
      - ./db_init:/docker-entrypoint-initdb.d  # Mount folder with SQL scripts
    ports:
      - "3306:3306"                          # Map MySQL port 3306 to host
    command: --skip-ssl
    networks:
      - mysql_net

networks:
  mysql_net:
    driver: bridge
